### ISSUE TITLE
Regarding using start-app and other requests.

### ISSUE THREAD

**Issue by kunjee17** [maciejsmolinski/elm-playground#1]
Hi, 

Thanks for pulling up great examples and hope it will be go on with other cool examples. Here are few questions and suggestion. Please don't mind to strike out any or all of it. If that doesn't match your roadmap. 
- Both application we are not using start-app? While Elm-Architecture and other samples (tutorial) are using it. Is there any special reason? Doesn't it be good to have start-app version also?
- Can't we have running example? Biggest hurdle in compare to pure javascript I find with ELM is that missing playground where we can throw code and run things. Or may be I don't know of one. Right now all languages having that kind of support. Just to get feel or connection between code and working example. 
- Is there any plan put more example in parallel with other frameworks. [elm-tutorial](http://www.elm-tutorial.org/) is great example of single page example using routing. And we can have more. It may be like giving clothes of apple to orange but my personal feeling is that bringing people from other framework would be easier if we are having similar examples. I my self coming from Angular and ditch React for Elm. And sole reason is I could found out above tutorial. 6 months back there are no library to deal with routing (for SPA) but now there are around 4 as last I remember. It is kind of required for BLOB (boring line of business) applications. 
- And my personal request. I m missing charts and graphics and all search and question give one direction that use ports. So, if you can give some examples with [C3](http://c3js.org/) or [D3](https://d3js.org/) or best way to do that? (even if we have to do with ports.)
- Continuing with that request. ELM do have wonderful http library. But in real time era I missing [Server Sent Events](http://stackoverflow.com/questions/35144530/how-to-capture-server-events-in-elm/35205602#35205602) and Sockets. So, example of that would be also helpful. 

PS: I don't want to influence your todo list for this project. So, please no need to change the queue. But if request come through that would be great. And If I can make something successful will surely try to give pull request.

**Comment by maciejsmolinski** [comment]
First, thanks a lot for taking time to post the issue @kunjee17!
I will try to answer your questions one by one below.

> 1) Missing StartApp

I'm a huge fan of understanding things before you start using libraries and frameworks (you feel much more control when you do that and you really know whether given library or framework is something you need).

This is why I decided to create first two projects without StartApp. There's one more I would like to create without it and then I'm more than happy to wrap everything you learn from them wiring that knowledge with StartApp.

> 2) Running Example

Great idea. What I can do in the first instance is to put these examples under some url that you can visit to see how things work before you actually clone the repository and set the project up locally. What do you think?

Not sure about the interactive environment, can't promise anything at the moment unless you have suggestions.

> 3) More examples in parallel with other frameworks

Is my understanding correct that having examples incorporating routing for example (a typical requirement in modern applications) would bring more people to Elm and be more attractive to newcomers?

> 4) C3 and D3 examples,

I don't have much experience with C3 and D3 but I guess this can be a common problem. Is there any chance you could post some code examples or describe what is that you would like to achieve by wiring Elm with those libraries? That would help a lot.

> 5) WebSockets / EventSource

Not sure about the resolution yet but this could be a challenging project. Would love to do it at some point.

**Note:** Roadmap

There's no fixed roadmap. Things I'm sure I would like to add here in the nearest future are Effects and WebSockets. I'm totally open to your suggestions though.

**Note:** Everybody can help
- If you know Elm well enough and would like to help - feel free to open Pull Requests
- If you don't know Elm very well - post what parts of the language are most difficult for you to understand. What problems you typically face that you'd like to solve with Elm.

Again, thanks a lot for taking time to post your suggestions @kunjee17. Really valuable comments.
Please let me know if there's anything else I could possibly help with.

Thanks,
Maciej

**Comment by kunjee17** [comment]
@maciejsmolinski Hey, Thanks for detailed reply. 

Here is things for your mentioned points.
1. I got you point. And I guess I would also agree with that. I am helping few college students to learn Elm. And I will surely point out this thing. (I m more on F# side but loved Elm as my day job is in JavaScript. I hope I will not need to explain why I love Elm. :P )
2. If not hot loading, static example would also be great help. Elm site is doing hot loading buy I don't know how. May be once I got little time will try to find out. I personally feel that having running example always have impact. I first go and run sample and then start reading it. May be its me, but still samples are good thing. 
3. Yes. I surely will. Current elm is going in that direction (of business application) but parallels are missing. Like I have List and can do all things what underscore or lodash can do. May be even better. But there is no sample showing that. So, people like me or feel little left out in start. JavaScript is having quite a good ecosystem. May be best in all languages. You name it and you have that library. I agree throwing all in mixture can make things weird but daily purpose libraries should be there. Like toastr library to show notification. Routing you already mentioned. Example to show few example from underscore / lodash in Elm. Or what is alternative of [moment](http://momentjs.com/). These all are utilities I normally have before I start project. Nothing is framework specific as such. So, having their alternative or if alternative not present using them in conjunction with Elm core library examples would be great. In simple words datatime, arrays, collections, and UI samples would be great. 
4. I try to come up with sample. (I m also no expert in that.) But question was more over UI/graph libraries. Elm is having low level SVG library. But I m surely not going to use that for project. Sample how can I use already established libraries for graph with Elm or if there is any other alternatives to show data. (Just like above point it is typical business requirement.)
5. If you are starting something will love to join. At the max I can star your project. :). Basically I feel the need of Even Sourcing as I wanted to make one way reactive architecture. Means user click button and task added, event go to server(and get 200 ok back), then actor, then process, then database, then using server event back to user. So, no callback chain or return value from post. Instead proper one way stream all the way. And Elm don't have html5 api for Server Events. :(. 

Thanks for providing detailed answers and wonderful examples. Please let me know if you like to continue discussion on any topic. Or any other things.

PS: I m no expert in Elm. Just know my way out here and there. Currently learning and helping others to learn also. As I said more on F# side so I love my types and don't like null. Because of that Elm feels like home.

**Comment by maciejsmolinski** [comment]
@kunjee17 got one update:

> Running Example

Not very sophisticated but got some examples running under following url: http://elm-playground.maciejsmolinski.com/

Thanks again for a very detailed response. Got your points and I'm going to focus on more practical examples you mentioned next. Will keep you posted.

If there's anything you would like share (thoughts, ideas, anything) in the meantime - don't hesitate to do so!

Thanks,
Maciej

**Comment by kunjee17** [comment]
@maciejsmolinski wow. You are having god speed for completing request. Just a little suggestion if possible can you add project link (folder or file) in demo. So, that is easy to move there once people enjoyed the demo. 

PS: I recently checked the packages site and it is now growing at exponential rate. Libraries like i18 was missing few months back and also libraries like simple form, time extra. Things are getting good , hopefully we will reach enough maturity to balance with React. :+1: 

Thanks for your effort on this.

**Comment by maciejsmolinski** [comment]
@kunjee17 Sure, I'm going to make proper linking once the next demo/project is rolled out. Thanks again for the suggestion.

Just to keep you posted, I just started working on a new project that uses `EventSource` as you suggested. Here's an early preview:

![](http://g.recordit.co/CIEUwDwvTP.gif)

What this is going to be eventually is a simple "live-match" widget that displays events that are happening on a football pitch during a fake match. All of that is available on `match-events` branch (https://github.com/maciejsmolinski/elm-playground/tree/match-events). Will let you know once it's ready.

Thanks,
Maciej

**Comment by maciejsmolinski** [comment]
@kunjee17 Actually managed to [roll the example out](http://elm-playground.maciejsmolinski.com/match-events/index.html).
You need to run `node server.js` locally to see things changing, check [README](https://github.com/maciejsmolinski/elm-playground#match-events-eventsource-integration) for details.

![](https://camo.githubusercontent.com/0ecf40b2f1f2f79bfcf3e99eaa340fe0ce55a096/68747470733a2f2f63646e2e706272642e636f2f696d616765732f326a4f456d6d395a2e676966)

You can build more things on top of that, this is a fairly simple example using ports to communicate with Elm application. Abstracting to an Elm package should also be possible but the point was to get it done as easily as possible.

Please let me know if you have questions about this one.

---

If you'd like to get two-way communication with the server, `WebSockets` are the way to go. Ports are your friend in such case.

Thanks,
Maciej

**Comment by kunjee17** [comment]
@maciejsmolinski man you sleep or not? You are seriously rock star. I may be selfish but can't hold my self but saying keep it coming. :+1:

**Comment by maciejsmolinski** [comment]
I do.. sporadically ;-) Wouldn't create those examples without your help @kunjee17!

In case you'd like to use `WebWorkers` in any of your Elm applications - I just changed `match-events` example to use them. The reason was to hide data source and move it out of the basic application skeleton.

You can now easily switch between Server-Sent-Events (uncomment line and run node.js server) and WebWorker-Generated-Events (no server needed). To see it working open http://elm-playground.maciejsmolinski.com/match-events/.

```
  (sse) Website <--postMessage|onmessage--> WebWorker <--postMessage|onmessage--> (EventSource <--keepalive--> Server)
(local) Website <--postMessage|onmessage--> WebWorker
```

Thanks again,
Maciej

**Comment by maciejsmolinski** [comment]
Here are the lines I'm talking about specifically: https://github.com/maciejsmolinski/elm-playground/blob/master/match-events/js/index.js#L8:L15

**Comment by maciejsmolinski** [comment]
@kunjee17 All demos are now more consistent visually and link to the main demos page where you can find link to the repository. Anything I possibly missed?
- http://elm-playground.maciejsmolinski.com/
- http://elm-playground.maciejsmolinski.com/match-events
- http://elm-playground.maciejsmolinski.com/randomuser
- http://elm-playground.maciejsmolinski.com/todo

![screen shot 2016-03-17 at 22 27 33](https://cloud.githubusercontent.com/assets/90652/13861863/f55071ee-ec8f-11e5-8878-3512a39414cd.png)

**Comment by maciejsmolinski** [comment]
Some of the items you posted in the first comment should already be addressed. Shall we review the list?

> 1) Missing StartApp

That's one of the things I'd love to address next. I was thinking about StartApp and Effects to manage more complex scenarios. Does it sound good to you?

> 2) Running Example

Even though not perfectly interactive, we've managed to put some examples live so that everybody can first see things before he or she decides to clone the project and play around with the code. Is there anything I missed with regards to this point?

> 3) More examples in parallel with other frameworks

So we've made an example that utilizes `WebWorkers` and `EventSource`. Good progress. Routing might come next along with the StartApp and Effects. What else would you like to see here? Any ideas?

> 4) C3 and D3 examples,

No updates on this really. Most of these libraries should come with sort of an `update` function ([like here for example](http://www.chartjs.org/docs/#line-chart-prototype-methods)) that could manage data changing over time. Not really sure how we could couple this with an Elm application.

> 5) WebSockets / EventSource

Project using `EventSource` along with `WebWorkers` already in the repository. Wouldn't be much of a difference if we used `WebSockets`. Even though they support two-way communication, it should be fairly easy to talk to them with ports. Please let me know if you need more clarification on this mate.

---

Anything I possibly missed @kunjee17 ? 

Thanks,
Maciej

**Comment by kunjee17** [comment]
@maciejsmolinski sir ji. You are making me embarrassed. I haven't done anything here. You are there on every line of code. Super awesome. :+1: 

I guess you haven't missed anything. A little suggestion though. I don't know if that looks good or not. That we can project link instead of back to demo or may be with demo there another link pointing to project. Like for todo example we will also have link for [todo repo](https://github.com/maciejsmolinski/elm-playground/tree/master/todo).

Now, for above list
1. Sounds good. You are thinking of anything specific?
2. Nope nothing missed as of now. Its looking great.
3. Here I have suggestion. I don't know how much feasible it is. When I start learning Elm around 8 months back there was no routing framework but now there are many. A kind of comparison or may be single example with reason why you chose specific one. Would be great. Right now I'm holding my self to HOP as it is getting matured (just moved to 3.0) and also in elm-tutorial it is used (same author). But again there are many. And will love have point of view from expert like you. 
4. Skip it for now. I guess just like Event Source ports will be way out here.
5. That was kind of awesome example. It is very much relevant for every time we fill need for external library or HTML5 functionality we just go in and out of Elm. 

I guess you are covering  ground like anything. Thanks for all your effort.

**Comment by maciejsmolinski** [comment]
Thanks again Kunjan! 

About linking to the source - that is now in place [for every demo](http://elm-playground.maciejsmolinski.com/). See example:

![screen shot 2016-03-19 at 13 53 13](https://cloud.githubusercontent.com/assets/90652/13898702/0fb0b0ee-edda-11e5-8f97-70b1159b9be6.png)

About the other things:

1) Sounds good. You are thinking of anything specific?

Nothing specific at this stage unless you have some ideas. If not, then I'll figure something out. Will keep you posted on this of course.

> 2) Nope nothing missed as of now. Its looking great.

Cool and thanks again for your help!

> 3) (Routing) A kind of comparison or may be single example with reason why you chose specific one.

Sure, will try to figure something out. Might be a good thing to couple with the first point (StartApp and Effects) so we grow from smaller examples to some bigger ones. I'm not an expert but will do my best ;-)

> 4) Skip it for now

Sure. Feel free to let me know if you struggle with this at any point. Will try to help out.

> 5) It is very much relevant for every time we fill need for external library or HTML5 functionality we just go in and out of Elm.

Glad the example helped!

Many thanks,
Maciej

**Comment by kunjee17** [comment]
@maciejsmolinski :+1: 

Thanks for your all work.

**Comment by maciejsmolinski** [comment]
Thanks again @kunjee17 for all you help and suggestions. I'm closing the issue since core issues have been resolved (some new examples introduced).

All projects are running perfectly fine under Elm 0.17 now.

Also, started a new project on a separate branch but I don't expect it to be released very soon. Will do my best though.

Let me know if there's anything else I can help with.

Thanks
Maciej
